# Generated by Django 3.2.7 on 2022-02-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('asset_class', models.CharField(max_length=10)),
                ('data', models.JSONField()),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SymbolList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbols', models.JSONField()),
                ('asset_class', models.CharField(max_length=10)),
                ('source', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
